# Generated by Django 4.2 on 2023-04-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveportal',
            name='email',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='saveportal',
            name='endDate',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='saveportal',
            name='leaveType',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='saveportal',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='saveportal',
            name='reason',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='saveportal',
            name='startDate',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
