# Generated by Django 4.2 on 2023-04-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveportal',
            name='reason',
            field=models.CharField(max_length=50),
        ),
    ]
