# Generated by Django 4.2 on 2023-04-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='savePortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=250)),
                ('leaveType', models.CharField(max_length=250)),
                ('startDate', models.CharField(max_length=250)),
                ('endDate', models.CharField(max_length=250)),
                ('reason', models.CharField(max_length=50)),
            ],
        ),
    ]
